/**
 * AI image generation using Google Imagen (via @google/genai)
 * Uses imagen-4.0-generate-001 for manga panel illustrations
 */
import { GoogleGenAI } from '@google/genai'

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_AI_API_KEY! })

export async function generateImage(promptEn: string): Promise<Buffer> {
  const mangaPrompt = `${promptEn}. anime illustration style, clean line art, pastel colors, simple background. IMPORTANT: absolutely no text, no speech bubbles, no dialogue boxes, no captions, no written words, no letters anywhere in the image`

  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt: mangaPrompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '4:3',
    },
  })

  const imageBase64 = response.generatedImages?.[0]?.image?.imageBytes
  if (!imageBase64) throw new Error('No image generated by Imagen')

  return Buffer.from(imageBase64, 'base64')
}

export async function generateCharacterSheet(
  characterName: string,
  promptDescription: string
): Promise<Buffer> {
  const prompt = `Character design sheet for ${characterName}: ${promptDescription}, Japanese manga anime style, full body portrait, white background, clean line art, pastel colors, professional character illustration`
  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '3:4',
    },
  })

  const imageBase64 = response.generatedImages?.[0]?.image?.imageBytes
  if (!imageBase64) throw new Error('No character image generated')

  return Buffer.from(imageBase64, 'base64')
}
